### ISSUE TITLE
Setting execution_summary to False causes an error in d6tflow.run()

### ISSUE THREAD

**Issue by marcietran** [d6t/d6tflow#29] opened 2021-02-22 22:45 UTC
I am using d6tflow version 0.2.2 and Luigi version 3.0.2. I tried setting `d6tflow.settings.execution_summary` to `False` and ran into an error when trying to run a task using `d6tflow.run()`

The error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[My Package Path]\venv\lib\site-packages\d6tflow\__init__.py", line 116, in run
    if abort and not result.scheduling_succeeded:
AttributeError: 'bool' object has no attribute 'scheduling_succeeded'
```

I investigated the source code at `\d6tflow\__init__.py` and found that if `execution_summary` is False, not having `detailed_summary = True` for `luigi.build` causes `result` to only be a boolean object, and thus does not have the attribute `scheduling_succeeded` (`luigi.build` source code is [here](https://github.com/spotify/luigi/blob/master/luigi/interface.py)). It could be fixed by simply removing the `execution_summary` condition in the first `if` statement, but perhaps there's a more appropriate solution 

Source code of interest:
```
if execution_summary and luigi.__version__>='3.0.0':
        opts['detailed_summary']=True
    result = luigi.build(tasks, **opts)
    if abort and not result.scheduling_succeeded:
        raise RuntimeError('Exception found running flow, check trace. For more details see https://d6tflow.readthedocs.io/en/latest/run.html#debugging-failures')
```

**Comment by Fire-Hound** [comment] 2021-03-01 19:10
Thanks for raising the issue!  Looked into this and it was indeed because `result` was morphing into a boolean when `execution_summary` is `False`.

This will be fixed in the upcoming version.

**Closed** 2021-03-15 23:55 UTC

**Comment by Fire-Hound** [comment] 2021-03-21 14:52
@marcietran 
If you have the time, can you check if the problem is solved?

**Comment by marcietran** [comment] 2021-03-23 18:50
@Fire-Hound It looks solved, thank you!
